version: '3.5'  

services:
  database:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
